version: '2.3'

services:
  tomcat:
    build:
      context: .
      args:
        JDK_VERSION: 8
        TOMCAT_VERSION: 9.0.12-jre8
    environment:
      CATALINA_OPTS: '-javaagent:/usr/local/tomcat/elastic-apm-agent.jar -Delastic.apm.service_name=tomcat -Delastic.apm.application_packages=de.eng -Delastic.apm.server_urls=http://apm-server:8200'
    ports:
      - 8000:8080
