metricbeat.modules:

  # This module fetches metrics from Docker containers.
  # The default metricsets are: container, cpu, diskio, healthcheck, info, memory and network.
  # The image metricset is not enabled by default.
  # https://www.elastic.co/guide/en/beats/metricbeat/current/metricbeat-module-docker.html
  - module: docker
    metricsets:
      - "container"
      - "cpu"
      - "diskio"
      - "healthcheck"
      - "info"
      - "image"
      - "memory"
      - "network"
    hosts:
      - "unix:///var/run/docker.sock"
    period: 10s
    enabled: true

  # The System module allows you to monitor your servers.
  # Because the System module always applies to the local server,
  # the hosts config option is not needed.
  # The default metricsets are cpu, load, memory, network, process and process_summary.
  # https://www.elastic.co/guide/en/beats/metricbeat/current/metricbeat-module-system.html
  - module: system
    metricsets:
      - cpu             # CPU usage
      - load            # CPU load averages
      - memory          # Memory usage
      - network         # Network IO
      - process         # Per process metrics
      - process_summary # Process summary
      - uptime          # System Uptime
      - core            # Per CPU core usage
      - diskio          # Disk IO
      - filesystem      # File system usage for each mountpoint
      - fsstat          # File system summary metrics
      - socket          # Sockets and connection info (linux only)
    processes: ['.*']
  
    # Configure the metric types that are included by these metricsets.
    cpu.metrics:  ["percentages"]  # The other available options are normalized_percentages and ticks.
    core.metrics: ["percentages"]  # The other available option is ticks.

    period: 10s
    enabled: true

  # This module periodically fetches metrics from Nginx servers.
  # The default metricset is stubstatus.
  # https://www.elastic.co/guide/en/beats/metricbeat/current/metricbeat-module-nginx.html
  - module: nginx
    metricsets:
      - "stubstatus"
    hosts:
      - "http://nginx"
    server_status_path: "status"
    period: 30s
    enabled: true

  # This module collects metrics from Jolokia agents running on a target JMX server
  # or dedicated proxy server. The default metricset is jmx.
  # The jmx metricset collects metrics from Jolokia agents.
  # https://www.elastic.co/guide/en/beats/metricbeat/current/metricbeat-metricset-jolokia-jmx.html
  # https://www.elastic.co/blog/brewing-in-beats-add-support-for-jolokia-lmx
  # https://www.elastic.co/de/blog/monitoring-java-applications-with-metricbeat-and-jolokia
  - module: jolokia
    metricsets:
      - "jmx"
    hosts:
      - "tomcat:8080"
    namespace: "tomcat"
    path: "/jolokia/?ignoreErrors=true&canonicalNaming=false"
    username: "jolokia"
    password: "jolokia"
    jmx.mappings:
      - mbean: "java.lang:type=Runtime"
        attributes:
          - attr: "Uptime"
            field: "uptime"
      - mbean: "java.lang:type=Memory"
        attributes:
          - attr: "HeapMemoryUsage"
            field: "memory.heap_usage"
            event: "memory"
          - attr: "NonHeapMemoryUsage"
            field: "memory.non_heap_usage"
            event: "memory"
      - mbean: "java.lang:type=Threading"
        attributes:
          - attr: "ThreadCount"
            field: "thread.count"
            event: "threads"
          - attr: "DaemonThreadCount"
            field: "thread.daemon"
            event: "threads"
      # Tomcat thread pools
      - mbean: "Catalina:name=*,type=ThreadPool"
        attributes:
          - attr: "currentThreadCount"
            field: "thread.count"
            event: "catalina"
          - attr: "maxThreads"
            field: "thread.max"
            event: "catalina"
          - attr: "connectionCount"
            field: "connection.count"
            event: "catalina"
      # GC Metrics
      # Check curl -X GET 'jolokia:jolokia@localhost:8000/jolokia/read/java.lang:type=GarbageCollector,name=*' | jq .
      - mbean: "java.lang:type=GarbageCollector,name=G1 Old Generation"
        attributes:
          - attr: "CollectionTime"
            field: "gc.old.cms_collection_time"
            event: "gc"
          - attr: "CollectionCount"
            field: "gc.old.cms_collection_count"
            event: "gc"
      - mbean: "java.lang:type=GarbageCollector,name=G1 Young Generation"
        attributes:
          - attr: "CollectionTime"
            field: "gc.young.cms_collection_time"
            event: "gc"
          - attr: "CollectionCount"
            field: "gc.young.cms_collection_count"
            event: "gc"
    period: 30s
    enabled: true

output.elasticsearch:
  hosts:
    - "${ELASTICSEARCH}"

setup.kibana:
  host: "${KIBANA}"
